compile:
	@gcc -c compare.c
	@gcc -c arithmetic.c
	@gcc -c addnew.c
	@gcc -c subnew.c
	@gcc -c mulnew.c
	@gcc -c abs.c
	@gcc -c pownew.c
	@gcc -c divnew.c
	@gcc compare.o addnew.o subnew.o mulnew.o pownew.o abs.o divnew.o arithmetic.o -o Hello
	@./Hello
