mySqr: mySqr.c 
	@echo "Compiling: mySqr.c -> mySqr.o"
	@gcc -c mySqr.c
	@echo "mySqr.c successfully compiled"
	@echo "Moving mySqr: /Top/1 -> /Top/obj"
	@mv mySqr.o ../obj/mySqr.o

clean:
	@echo "Removing mySqr"
	@rm ../obj/mySqr.o
