mySqrt: mySqrt.c
	@echo "Compiling: mySqrt.c -> mySqrt.o"
	@gcc -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c mySqrt.c
	@echo "mySqrt successfully compiled"
	@echo "Moving mySqrt.o: /Top/4 -> /Top/obj"
	@mv mySqrt.o ../obj/mySqrt.o
clean:
	@echo "Removing mySqrt"
	@rm ../obj/mySqrt.o
