myCOP: myCOP.c
	@echo "Compiling: myCOP.c -> myCOP.o"
	@gcc -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c myCOP.c
	@echo "myCOP successfully compiled"
	@echo "Moving myCOP.o: /Top/3 -> /Top/obj"
	@mv myCOP.o ../obj/myCOP.o
clean:
	@echo "Removing myCOP"
	@rm ../obj/myCOP.o
